[package]
authors = ["Mario Nebl <hello@mario-nebl.de>"]
name = "flik-rs"
version = "0.1.0"

[dependencies]
clap = "2.29.2"
text_io = "0.1.7"
rpassword = "2.0.0"

[dev-dependencies]
assert_cli = "0.5.4"
