[package]
authors = ["Mario Nebl <hello@mario-nebl.de>"]
name = "flik-rs"
version = "0.1.0"

[dependencies]
clap = "2.29.2"
futures = "0.1.18"
tokio-core = "0.1.12"
tokio-proto = "0.1.1"
tokio-service = "0.1.0"

[dev-dependencies]
assert_cli = "0.5.4"
